"""Add CASCADE to grades teacher_id

Revision ID: 60d44fefba71
Revises: 57efda735fea
Create Date: 2025-12-01 22:27:16.604613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d44fefba71'
down_revision: Union[str, Sequence[str], None] = '57efda735fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('grades_teacher_id_fkey'), 'grades', type_='foreignkey')
    op.drop_constraint(op.f('grades_student_id_fkey'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'teachers', ['teacher_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grades', 'students', ['student_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('grades_student_id_fkey'), 'grades', 'students', ['student_id'], ['user_id'])
    op.create_foreign_key(op.f('grades_teacher_id_fkey'), 'grades', 'teachers', ['teacher_id'], ['user_id'])
    # ### end Alembic commands ###
