"""add teacher fields

Revision ID: dac54e36d7cc
Revises: a77d5e97b5e1
Create Date: 2025-11-30 17:12:20.375248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac54e36d7cc'
down_revision: Union[str, Sequence[str], None] = 'a77d5e97b5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ Adăugăm coloana TEMPORAR ca NULLABLE
    op.add_column(
        'classes',
        sa.Column('teacher_id', sa.UUID(), nullable=True)
    )

    # 2️⃣ Creăm foreign key
    op.create_foreign_key(
        'fk_classes_teacher',
        'classes',
        'teachers',
        ['teacher_id'],
        ['user_id']
    )

    # 3️⃣ Adăugăm câmpurile noi la teachers
    op.add_column(
        'teachers',
        sa.Column('subject', sa.String(), nullable=True)
    )
    op.add_column(
        'teachers',
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False)
    )
    op.add_column(
        'teachers',
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False)
    )

    # ⚠️ OPȚIONAL: dacă vrei să forțezi un teacher default
    # op.execute("UPDATE classes SET teacher_id = (SELECT user_id FROM teachers LIMIT 1)")

    # 4️⃣ DOAR DUPĂ ce datele există → îl faci NOT NULL (opțional)
    # op.alter_column('classes', 'teacher_id', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'updated_at')
    op.drop_column('teachers', 'created_at')
    op.drop_column('teachers', 'subject')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'teacher_id')
    # ### end Alembic commands ###
